/** Translate settings generated by the existing rendering-control components. */
const labels: [string, string][] = [
  ['阅读文章时，选择 SAVE ARCHIVE 将其保存在此处。', 'Choose SAVE ARCHIVE while reading to keep a file here.'],
  ['尝试其他标题、文章编号，或切换分类。', 'Try another title or file ID, or change the category.'],
  ['输入文章编号、标题或分类', 'Enter a file ID, title or category'],
  ['FILE / 文章', 'FILE / ARTICLE'], ['CATEGORY / 分类', 'CATEGORY'],
  ['尚无收藏文章', 'No saved articles'], ['没有匹配的文章', 'No matching articles'],
  ['查看全部文章', 'View all articles'], ['重置检索', 'Reset search'],
  ['收藏文章', 'Saved articles'], ['文章检索', 'Article search'],
  ['系统设置', 'System settings'], ['收藏档案', 'Saved files'], ['档案检索', 'Archive search'],
  ['三维画面以 50% 分辨率、最高 60 帧运行；关闭后恢复所选画质', 'Runs the 3D scene at 50% resolution and up to 60 fps; turn off to restore the selected quality'],
  ['完整、减少或按分项自定义；关闭后会立即收束当前动画（开场设置下次重播生效）', 'Use full or reduced motion, or adjust individual effects. Boot changes apply on replay.'],
  ['即时生效并自动保存。清晰度与材质设置同步至 360° 查看器。高渲染比例更适合静态观察；缓冲上限为 829 万像素，硬件限制时自动收敛。', 'Changes apply immediately and are saved. Resolution and material settings also affect the 360° viewer. The render buffer is limited to 8.29 million pixels.'],
  ['每次启动都会读取 Wallpaper Engine 中的设置。在此修改仅对当前运行生效，无法持久保存；如需保留，请在 Wallpaper Engine 的壁纸属性中调整。', 'Wallpaper Engine settings are loaded at each start. Changes here apply only to this session.'],
  ['开场 / 阵列 / 详情 / 界面 / 360° 查看器', 'Boot / Array / Detail / Interface / 360° Viewer'],
  ['相对屏幕像素，受密度上限限制；高比例改善细线', 'Relative to screen pixels; a higher value sharpens fine lines'],
  ['控制高密度屏幕的原生像素倍率', 'Limits native pixel density on high-density screens'],
  ['SMAA 平滑模型边缘与后处理结果', 'SMAA smooths model edges and post-processing'],
  ['改善倾斜视角下的标签细节', 'Improves label detail at oblique angles'],
  ['控制盖板折射画面的清晰度', 'Controls clarity through the transparent cover'],
  ['更高分辨率保留更细的投影边缘', 'Higher resolution keeps finer shadow edges'],
  ['采样越多，接缝暗部越细腻', 'More samples refine dark seams'],
  ['降低可减轻环境遮蔽的渲染负担', 'Lower values reduce ambient occlusion cost'],
  ['0% 关闭；100% 保留原始镜头虚化', '0% disables blur; 100% keeps the original lens effect'],
  ['拖动阵列或点击界面按钮浏览档案。桌面模式下，方向键与滚轮可能无法传入壁纸。', 'Drag the array or use the controls to browse files. Wallpaper Engine may not pass arrow keys or scrolling through.'],
  ['玻璃阵列随配色逐张过渡', 'The glass array transitions with the theme'],
  ['开机标志、扫描与欢迎画面', 'Logo, scan and welcome screen'],
  ['选档时向阵列传播的波浪', 'Wave spreading through the array when selecting a file'],
  ['停止操作后的阵列起伏', 'Array motion while idle'],
  ['镜头随指针的轻微偏移', 'Subtle camera movement with the pointer'],
  ['松手后按实际速度继续滑行', 'Continue sliding after release'],
  ['切列、切档时的轨道移动', 'Track movement when changing columns or files'],
  ['抽取、转正、归位与详情镜头', 'Extraction, rotation, return and detail camera'],
  ['模型解密线与磨砂揭示', 'Model scan and frosted-glass reveal'],
  ['正文的遮罩揭示', 'Text reveal mask'],
  ['标题、分类与权限标签滚动', 'Rolling titles, categories and access labels'],
  ['序号、列编号与档案编码滚动', 'Rolling counters and file IDs'],
  ['详情、检索、收藏与设置窗口过渡', 'Detail, search, saved and settings transitions'],
  ['360° 旋转、平移、缩放与复位阻尼', '360° rotate, pan, zoom and reset easing'],
  ['拆解、重组与清晰度变化', 'Disassembly, reassembly and clarity changes'],
  ['切列', 'Columns'], ['选档', 'Files'], ['读取', 'Read'], ['返回', 'Back'], ['搜索', 'Search'],
  ['界面配色', 'Color theme'], ['亮色', 'Light'], ['暗色', 'Dark'],
  ['完整动画', 'Full motion'], ['减少动画', 'Reduced motion'],
  ['预设', 'Preset'], ['选择会保存在本站', 'Saved on this site'],
  ['当前使用完整动画。', 'Full motion is active.'], ['当前已减少动画。', 'Reduced motion is active.'],
  ['当前使用自定义动画', 'Custom motion is active'],
  ['启用完整动画并重播', 'Enable full motion and replay'],
  ['动效设置', 'Motion settings'], ['开场', 'Boot'], ['档案阵列', 'Archive array'],
  ['档案详情', 'File detail'], ['界面', 'Interface'], ['360° 查看器', '360° Viewer'],
  ['完整', 'Full'], ['减少', 'Reduced'], ['自定义', 'Custom'],
  ['精细设置', 'Advanced settings'], ['清晰度 / 材质 / 阴影', 'Clarity / Materials / Shadows'],
  ['渲染画质', 'Render quality'], ['画质设置', 'Quality settings'], ['画质预设', 'Quality preset'],
  ['渲染比例', 'Render scale'], ['像素密度上限', 'Pixel ratio limit'], ['抗锯齿', 'Antialiasing'],
  ['纹理过滤', 'Texture filtering'], ['透明材质分辨率', 'Transparency resolution'],
  ['阴影分辨率 · 阵列', 'Shadow resolution · Array'], ['环境遮蔽 · 阵列', 'Ambient occlusion · Array'],
  ['遮蔽分辨率 · 阵列', 'Occlusion resolution · Array'], ['景深强度 · 阵列', 'Depth of field · Array'],
  ['性能', 'Performance'], ['原始', 'Original'], ['极高', 'Ultra'], ['高', 'High'],
  ['关闭', 'Off'], ['采样', 'samples'], ['开源许可', 'Open-source license'],
];

export function localizeSettings(root: HTMLElement) {
  const replace = (value: string) => labels.reduce((text, [from, to]) =>
    from.length <= 2 && from !== '采样' && text.trim() !== from ? text : text.replaceAll(from, to), value);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (node.textContent) node.textContent = replace(node.textContent);
  }
  root.querySelectorAll<HTMLElement>('[aria-label], [title], [placeholder]').forEach(node => {
    for (const attribute of ['aria-label', 'title', 'placeholder']) {
      const value = node.getAttribute(attribute);
      if (value) node.setAttribute(attribute, replace(value));
    }
  });
}
